### ISSUE TITLE
Unable to add cmd_tpl to commands: SqliteFailure

### ISSUE THREAD

**Issue by buster** [cantino/mcfly#17]
On Linux/Debian i have the following problem:

```
# RUST_BACKTRACE=1 mcfly -d search

McFly: Upgrading McFly DB to version 3, please wait...thread 'main' panicked at 'Unable to add cmd_tpl to commands: SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("duplicate column name: cmd_tpl"))', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:227
             at libstd/panicking.rs:476
   3: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   4: rust_begin_unwind
             at libstd/panicking.rs:325
   5: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   6: core::result::unwrap_failed
   7: mcfly::main
   8: std::rt::lang_start::{{closure}}
   9: main
  10: __libc_start_main
  11: _start
McFly: Upgrading McFly DB to version 3, please wait...thread 'main' panicked at 'Unable to add cmd_tpl to commands: SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("duplicate column name: cmd_tpl"))', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by buster** [comment]
Now it's this error:

```
RUST_BACKTRACE=1 mcfly -d search
thread 'main' panicked at 'Please ensure that MCFLY_SESSION_ID contains a random session ID.: NotPresent', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:227
             at libstd/panicking.rs:476
   3: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   4: rust_begin_unwind
             at libstd/panicking.rs:325
   5: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   6: core::result::unwrap_failed
   7: mcfly::settings::Settings::parse_args
   8: mcfly::main
   9: std::rt::lang_start::{{closure}}
  10: main
  11: __libc_start_main
  12: _start
```

**Comment by cantino** [comment]
It sounds like `mcfly.bash` isn't loaded in your shell? That should be setting `MCFLY_SESSION_ID`

**Comment by buster** [comment]
You're right. Initially, i had a similar error when loading the mcfly.bash.
Afterwards i only tested with "mcfly search".

Anyway, after removing the db file it seems to work :)

**Comment by cantino** [comment]
Glad it's working!

**Comment by mehta** [comment]
I had similar issue and in my case there were some bad-characters in my bash-history, it looks like:

```
$ cat .bash_history
   1   │ �^Awhich psql
   2   │ ^@exit
   3   │ ^@ksh
   4   | ls -l 
   5   | mkdir rex
   6 . | .. 
```
So I performed following steps:
1. Removed bad lines in ~/.bash_history (i.e. 1,2,3 in this case)
2. Deleted ~/.mcfly/history.db
3. source "$(brew --prefix)/opt/mcfly/mcfly.bash" ## For me, it was installed via homebrew
4.  RUST_BACKTRACE=1 mcfly -d search

and then everything works fine.

**Comment by mehta** [comment]
> @mehta, were you on v0.2.4 or newer when this happened?

$ brew info mcfly
cantino/mcfly/mcfly: stable v0.3.1
...

**Comment by Lomanic** [comment]
I'm trying `McFly 0.3.3` ([binary release x64](https://github.com/cantino/mcfly/releases/download/v0.3.3/mcfly-v0.3.3-x86_64-unknown-linux-gnu.tar.gz) and [manual install](https://github.com/cantino/mcfly/tree/c18da85537e14c0d93449c16c91e3d435c7ba917#installing-manually-from-github)) on Debian 9 and I'm encountering the same error

```
McFly: Upgrading McFly DB to version 3, please wait...thread 'main' panicked at 'McFly error: Unable to add cmd_tpl to commands: SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("duplicate column name: cmd_tpl"))', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Setting `export RUST_BACKTRACE=1`  adds the following backtrace 

```
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: main
  10: __libc_start_main
  11: <unknown>
```

For me `mcfly.bash` is properly sourced (MCFLY_SESSION_ID and MCFLY_HISTORY are set)

Here is the result of `export RUST_BACKTRACE=1 && rm ~/.mcfly/history.db`

``` 
McFly: Importing Bash history for the first time. This may take a minute or two...thread 'main' panicked at 'McFly error: Insert to work: NulError(NulError(0, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 49, 53, 51, 56, 56, 49, 51, 53, 49, 54]))', src/libcore/result.rs:1009:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: main
  10: __libc_start_main
  11: <unknown>
```

**Comment by cantino** [comment]
That looks like a new error, @Lomanic. I'll make a new issue for it.

**Comment by jesusfj710** [comment]
Hi @cantino, could we add this to the `readme.md` or something like `troubleshooting.md`?

> 
> 1. Removed bad lines in ~/.bash_history (i.e. 1,2,3 in this case)
> 2. Deleted ~/.mcfly/history.db
> 3. source "$(brew --prefix)/opt/mcfly/mcfly.bash" ## For me, it was installed via homebrew
> 4. RUST_BACKTRACE=1 mcfly -d search
>

**Comment by cantino** [comment]
@jesusfj710 Sure, would you mind sending a PR?
