### ISSUE TITLE
error if running multiple commands from different shells

### ISSUE THREAD

**Issue by mirage83** [cantino/mcfly#49]
I'm working with multiple bash shells and ran in the following error while I ran 3 commands in different shells:
thread 'main' panicked at 'McFly error: Unable to create schema_versions db table: SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

I'm using McFly version 0.3.3.

**Comment by cantino** [comment]
Sorry for the delay. This does sound like a real issue. Odd that I haven't had it happen myself.

**Comment by raivivek** [comment]
I can attest that this happens frequently with me as well. I am using v0.3.3.

**Comment by cantino** [comment]
Thanks, I'll try to fix it.

**Comment by cantino** [comment]
I've been unable to reproduce this, but have a possible fix in https://github.com/cantino/mcfly/pull/60. Would it be easy for either of you to test https://github.com/cantino/mcfly/pull/60?

**Comment by cantino** [comment]
@raivivek @mirage83 ^

**Comment by mirage83** [comment]
Can you provide a snapshot? I don't have Rust installed.
I don't have a reproducer for this issue. I just can use a snapshot and see if the issue reoccurs.

**Comment by cantino** [comment]
Sure! I included it in this release: https://github.com/cantino/mcfly/releases/tag/v0.3.4

**Comment by pmarreck** [comment]
ran into the same issue. and mcfly is generally taking many dozens of seconds after each command to return shell control to me. I've already limited the max history to 10K. Anything else I can do to either start over from a known-good place or repair the sqlite DB or...?
```
thread 'main' panicked at 'McFly error: Unable to create schema_versions db table (database is locked)', src/history/schema.rs:105:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
FWIW I'm on NixOS currently.

**Comment by cantino** [comment]
Hi @pmarreck, I'm sorry to hear that. I haven't seen this before. According to [this StackOverflow page](https://stackoverflow.com/questions/151026/how-do-i-unlock-a-sqlite-database), you could try copying the DB and moving it back:

```
mv ~/.mcfly/history.db temp.db
cp temp.db ~/.mcfly/history.db
```

Or something similar.

**Comment by pmarreck** [comment]
Tried that, didn't help, but I realized that all of my disk operations seem slow as well, so I may have a disk issue; I'm going to look into how to troubleshoot slow disk ops in Linux (any tips welcome of course)
